services:
   medhelper:
      build: .
      ports:
         - 80:3000
      environment:
         - NODE_ENV=development
         # - NODE_ENV=production
      env_file:
         - .env
         - .env.local
