version: "3.9"

services:
   web:
      build:
         context: .
         dockerfile: Dockerfile
      ports:
         - "80:3000"
      environment:
         NODE_ENV: production
      env_file:
         - .env
      restart: always
