import type { Metadata } from "next";
import { Toaster } from "@/components/ui/sonner"
import { SessionProvider } from "next-auth/react";
import "./globals.css";
import SideBar from "@/components/partails/sidebar";

export const metadata: Metadata = {
  title: "Welcome to Med Helper",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <Toaster />
        <SessionProvider>
          <div className="flex flex-grow h-screen overflow-hidden">
            <SideBar />
            <div className="flex-1 bg-[#F2F8FC] overflow-auto max-h-screen">
              {children}
            </div>
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}
