import type { Metadata } from "next";
import { Toaster } from "@/components/ui/sonner"
import { SessionProvider } from "next-auth/react";
import "./globals.css";

export const metadata: Metadata = {
    title: "Welcome to Med Helper",
    description: "Generated by create next app",
    icons: {
        icon: "/favicon.png",
    }
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`antialiased`}
            >
                <Toaster />
                <SessionProvider>
                    {children}
                </SessionProvider>
            </body>
        </html>
    );
}
